name: future_store
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  connectivity_plus: ^2.3.5
  freezed_annotation: ^2.0.3
  http: ^0.13.4
  intl: ^0.17.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  bloc_test: ^9.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Kantumruy
      fonts:
        - asset: assets/fonts/KantumruyPro-Regular.ttf
        - asset: assets/fonts/KantumruyPro-Medium.ttf
        - asset: assets/fonts/KantumruyPro-SemiBold.ttf
        - asset: assets/fonts/KantumruyPro-Bold.ttf
